CREATE ROLE "gocd_user" PASSWORD 'zJY5ejXBM5oG9' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
CREATE DATABASE "gocd" ENCODING="UTF8" TEMPLATE="template0";
GRANT ALL PRIVILEGES ON DATABASE "gocd" TO "gocd_user";
ALTER ROLE "gocd_user" SUPERUSER;